let nombre = "John"
let apellido = "Doe"
let estudiante = `${nombre} ${apellido}`
let estudianteMayus = estudiante.toUpperCase()
let estudianteMinus = estudiante.toLowerCase()
let numeroLetras = estudiante.length
let primeraLetraNombre = nombre.charAt(0)
let ultimaLetraApellido = apellido[apellido.length - 1]
let eliminaEspacios = estudiante.trim()
let isNombreInEstudiante = estudiante.includes(nombre)
